services:

  nginx:
    build: ./nginx
    ports:
      - 9980:80
      - 9443:443
    volumes:
      - acme-challenge:/var/www/certbot:ro
      - certs:/etc/nginx/ssl:ro
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro

  certbot:
    build: ./certbot
    volumes:
      - acme-challenge:/var/www/certbot:rw
      - certs:/etc/letsencrypt:rw
      # - ./config/certbot-cli.ini:/etc/letsencrypt/cli.ini:ro
      - ./config/certbot-certs.list:/etc/letsencrypt/certs.list:ro

volumes:
  acme-challenge:
  certs:
