services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - internet
      - internal_revproxy
    volumes:
      - acme-challenge:/var/www/certbot:ro
      - certs:/etc/nginx/ssl:ro
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro

  certbot:
    build: ./certbot
    networks:
      - internet
    volumes:
      - acme-challenge:/var/www/certbot:rw
      - certs:/etc/letsencrypt:rw
      # - ./config/certbot-cli.ini:/etc/letsencrypt/cli.ini:ro
      - ./config/certbot-certs.list:/etc/letsencrypt/certs.list:ro

volumes:
  acme-challenge:
  certs:

networks:
  internet:
  internal_revproxy:
    name: internal_revproxy
    internal: true
